### ISSUE TITLE
Feature request: Only tell the last played move

### ISSUE THREAD

**Issue by mujehoxe** [jeffarjeffar/Chess_Bot#11]
This will improve visualization and it is the reason i am searching for chess chatbots in the first place.

**Comment by dlee888** [comment]
What exactly do you mean? Do you want it to delete the previous messages each time it sends a new one?

**Comment by mujehoxe** [comment]
No, there should be an option to stop viewing the board at all, only giving the move that happened last.

**Comment by dlee888** [comment]
By giving the move do you mean the text of the move? You need to see the board to know where the bot has moved.

**Comment by mujehoxe** [comment]
No you don't have to if you know chess well, the positions on the board and the FEN notation.

**Comment by mujehoxe** [comment]
You can take a look at some yt vids on blindfold chess.

**Comment by dlee888** [comment]
So do you want an option for blindfold chess? there is already a theme for that
It would be impractical to remove the board entirely, as most people don't want to play blindfold

**Comment by mujehoxe** [comment]
Those people should keep the board enabled.

**Comment by dlee888** [comment]
Closing as I don't think this will be a feature useful for the vast majority of people.
